# Introduction to OOP in Python
 one of the popular approach to solve a programming probleb by creating an objects. This is known as Object Oriented Programming.     
An object has two characterstics:    
1.attributes(name,age,colour)   
2.behaviour(learn,study,singing,dance)   

In Python, the concept OOP follow these things:   

1.Inheritance  
2.Encapsulation  #wrapping data into single unit    
3.Ploymorphism  
 
Class:  
A class is blueprint of the object or logical entity   

Object:  
Blueprint of class or Instance of the class or physical entity  

Methods:   
Part of class and can be called with object   

Constructors: 
Part of class and can be called aotomatically when the obj of class is created


In [ ]:
class ClassName:
    #some functions and variables
    #function--used to perform the specific activity
    #variables--Data(memory)

In [4]:
def test():
    print('Test() for function')
    return
test()

Test() for function


In [5]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return

obj=Demo()  #object creation
obj.test() #call for the method

test() for the class and method


In [8]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
p1.fact(5)#120

120

In [ ]:
#Method
# def test(self,para1,para2)

In [14]:
class Demo2:
    def Accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        a=p1
        b=p2
        return
    def display(self):
        print("p1=",p1)
        print("p2=",p2)
c1=Demo2()
c1.accept(10,20)
c1.display()

AttributeError: 'Demo2' object has no attribute 'accept'

In [13]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [15]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [24]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [29]:
lst=[1.0,2.4,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [40]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)


(2, 3)


In [22]:
#Re-shape the given array
#numpy.reshape(arrayName,reshape,order='C')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
#append some data--horizontally
#hstack(array1,array2)--will be automatically arranged in horizontal
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [32]:
#append some data--verlically
#vstack(array1,array2)--will be automatically arranged in vertical
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [33]:
#Generate random number from NP
a1=np.random.normal(5,0.5,10)
print(a1)

[5.76290142 4.8477032  4.53554613 5.85001176 5.13109601 5.59706925
 6.11070675 4.27858796 3.69732172 3.9371804 ]


In [35]:
#numpy.zeros() and numpy.one()
#Generate an array with all zeroes--numpy.zeros()
#numpy.zeroes(shape,dtype=float,order='C')

np.zeros((2,2))


array([[0., 0.],
       [0., 0.]])

In [38]:
np.zeros((2,2),dtype=np.int32)

array([[0, 0],
       [0, 0]])

In [39]:
#np.ones(shape,dtype=float,order='C')
np.ones((4,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [42]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [43]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [44]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [45]:
#arange()--particular
#numpy.arrange(start,end,step)
#start-value
#end-value
#step-gap bet one value to another value
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [47]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [48]:
#Index and slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [49]:
a1=np.array([(1,2,3),(4,5,6)])
print("First Row:",a1[0])

First Row: [1 2 3]


In [50]:
a1=np.array([(1,2,3),(4,5,6)])
print("Second Row:",a1[1])

Second Row: [4 5 6]


In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Column:",a1[:,1])

Slicing Column: [2 5]


In [53]:
a1=np.array([(1,2,3),(4,5,6)])
print("Slicing Last Column:",a1[:,2])

Slicing Last Column: [3 6]


In [54]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and Column",a1[1,:2])

Row and Column [4 5]


In [55]:
a1=np.array([(1,2,3),(4,5,6)])
print("Row and Column",a1[1,:1])

Row and Column [4]


In [56]:
a1=np.array([(1,2,3),(4,5,6)])
print("First row",a1[1][1])

First row 5


In [57]:
a1=np.random.normal(5,1,10)
print(a1)

[6.12871744 5.40051271 5.72960962 5.87245782 3.40175392 4.02916713
 4.54662039 4.80462614 3.66702254 4.1274049 ]


In [58]:
#Some math Operation on givrn random numbers
#Min--returns the least number
#Max--returns the Large number
#Mean--Mean
#Median--Median
#GD--Gaussian Distribution
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[4.56382663 6.98533976 5.15941093 4.71991981 4.66334854 3.71038005
 4.7995859  4.04419335 5.56261467 5.8006482 ]
Min value= 3.710380048151011
Max value= 6.985339761173357
Mean value= 5.000926784726497
Median value= 4.75975285825902


In [59]:
#Multiply of 1D arrays
#numpy.dot(x,y)--
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [60]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [64]:
b1=np.array([([1,5]),([6,9])])
b2=np.array([([1,3]),([1,6])])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

# Pandas Basics
 Python is one of the popular programming language for data analysis<br>    
Python is offering the Lib called Pandas used for importing and analysing pretty much faster and easier also        
Pandas DataFrames        
    
    Data Analysis with Python    
     

In [67]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"MobileNumber":[999,888,777,888,777,999],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"],}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd


In [68]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  MobileNumber Address
01    Anil    anil@gmail.com           999     Hyd
02   Akhil   akhil@gmail.com           888     Hyd
03  Dinesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           888     Hyd
05    Ajay    ajay@gmail.com           777     Hyd
06  Kranth  kranth@gmail.com           999     Hyd


In [ ]:
#supermarket.csv-Analysis(which product having higher %of selling price)
#which product having least selling %

import pandas as pd
products=pd.read__csv('FileName.csv')
print(products)

In [ ]:
import pandas as pd
product_sellingData=pd.read_csv('FileName.csv',index_col=1)
print(product_sellingData)